time = int(input("Введите время в секундах >>>"))
hours = (time // 3600)
seconds = (time - hours * 3600 )
minutes = (seconds // 60)
seconds_final = (seconds - minutes * 60)
print(f"{hours} : {minutes} : {seconds_final}")
